name: loaded-dice
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pooch
  - py7zr
  - pyarrow
  - scipy
  - pip
  - pip:
    - -e ../fair2.1-calibrate

